version: '3.7'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
#    ports:
#      - 27017:27017
#    volumes:
#      - /Users/mac/workspace/pycharm/csdn/data:/data/db
    container_name: csdn-mongodb
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    container_name: csdn-mongodb-express
#  selenium:
#    image: selenium/standalone-chrome
#    volumes:
#      - /dev/shm:/dev/shm
#    restart: always
#    ports:
#      - 6666:4444
#    container_name: selenium
  csdn:
    build: .
    image: csdn-spider:latest
    volumes:
      - ./:/csdn/
    restart: "no"
    #  --loglevel INFO
    command: scrapy crawl Resource --loglevel INFO
    container_name: csdn-resource